### ISSUE TITLE
Shut down ethereum/wiki

### ISSUE THREAD

**Issue by bmann** [ethereum/eth-wiki#3]
There is confusion about this wiki and the ethereum/wiki. I'm filing an issue over there about shutting it down / archiving it.

**Comment by virgil** [comment]
Agreed.  I'd actually like to move eth-wiki to be under the Ethereum github repo if they'll accept it.

**Comment by ChrisChinchilla** [comment]
Now partially in progress 🎉

**Comment by ChrisChinchilla** [comment]
We are getting closer!

**Comment by samajammin** [comment]
Closing this out as done 👍 - see https://github.com/ethereum/wiki/wiki
