### ISSUE TITLE
Don't require login to see edit button.

### ISSUE THREAD

**Issue by MicahZoltu** [ethereum/eth-wiki#44]
Submitting change suggestions to a wiki should be easy.  I shouldn't have to login to see an "Edit on GitHub" button.

**Comment by ChrisChinchilla** [comment]
Thanks @MicahZoltu we are covering this in #41 so I will close this issue. We need to think quite carefully about this as the old wiki was frequently vandalised, and wiki.js doesn't have the best permissions system, but we are figuring it out.
