### ISSUE TITLE
The Web 3.0 term is already reserved, please stop promoting it

### ISSUE THREAD

**Issue by bodqhrohro** [ethereum/eth-wiki#59]
Jason Calacanis [had described it](https://calacanis.com/2007/10/03/web-3-0-the-official-definition/) as "the creation of high-quality content and services produced by gifted individuals" way back in 2007, before the cryptocurrency and blockchain movement had even emerged.

This definition describes pretty well services like Quora or Yandex.Q that try to verify the experts, unlike the previous generation of Q&A websites did. As well as the recent addition of "Verified" badges in numerous social media falls into that description. But it definitely has nothing to do with decentralization.

This leads to confusion when I have discussions with blockchain fans, as they know the Web 3.0 definition from the Ethereum propaganda, while I stick to the established one.

So please choose some other term for your movement. There are lots of numbers above 3, and there is nothing despicable in skipping some (remember Winamp 4 and PHP 6? ;)).

**Comment by bodqhrohro** [comment]
?

**Comment by timbeiko** [comment]
Sorry, but this isn't isn't really in the scope of this repo, nor is it really addressable @bodqhrohro: no one has a monopoly on the term.

**Comment by bodqhrohro** [comment]
Sure, the words can be arbitrarily re-defined, it happens all the time.
![photo_2021-07-09_21-20-11](https://user-images.githubusercontent.com/2134486/125120688-7b00df80-e0fb-11eb-85dd-228f71a3ae35.jpg)
What's the right place to discuss it then?

**Comment by timbeiko** [comment]
I'd suggest reddit.com/r/cryptocurrency to start a conversation :+1:

**Comment by bodqhrohro** [comment]
I don't use Reddit.
